### ISSUE TITLE
"Recent files" and "My files" are shared across all classeurs

### ISSUE THREAD

**Issue by krotton** [classeur/classeur#34]
I have created a bunch of classeurs to keep scopes of files separate - I keep various work-related documents in one classeur, generic memos created on the go in the other one and so on. However the "recent files" and filtering tabs do not limit the displayed results and include all files from all classeurs. I guess it's not a desired behaviour (and if it is, I'd argue it's confusing and unnecessary), because without the need for distinct file sets, one would just use folders.

I can fix it, but first I'd like to know whether that's intentional.

**Comment by benweet** [comment]
Yeah, I agree that's confusing. The problem is that some files can be orphan (not in any folder, so not attached to a particular classeur). I guess these ones can be shown in every classeur.
What do you think?

**Comment by krotton** [comment]
That's one option (and I think it's all right - although I'd rather keep the orphaned files visually separated from the ones belonging to the active classeur). Two more options I can think of are: keep a "ghost" classeur which contains all the orphans (and which is accessible through the "switch" menu) or just simply disallow files without a parent classeur.

**Comment by benweet** [comment]
Fixed in v0.12. Now, you have files from other classeurs in a separated list. Let me know what you think.

**Comment by krotton** [comment]
It's clear and works perfectly. Thanks!

**Comment by dotsomeone** [comment]
In chrome extension, v1.0.6, this issue still exists. Please reopen this issue or mark #107 as duplicate.
